[package]
name = "rusty-core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[workspace]
members = ["crates/*"]

[workspace.dependencies]
boltffi = "0.26.1"
redb = "4.1.0"
serde = { version = "1.0.229", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio"] }
tempfile = "3.27.0"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.26.0", features = ["v7"] }
serde_json = "1.0.151"

[dependencies]
rusty-macros = { path = "crates/rusty-macros" }
rusty-types = { path = "crates/rusty-types" }
rusty-kv = { path = "crates/rusty-kv" }

boltffi = { workspace = true }
redb = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
